export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const GET_ME = "GET_ME";
export const GET_ME_SUCCESS = "GET_ME_SUCCESS";
export const LOG_OUT = "LOG_OUT";
export const UPDATE_RULE_FIREWALL = "UPDATE_RULE_FIREWALL";
export const GET_LIST_FIREWALL = "GET_LIST_FIREWALL";
export const GET_LIST_FIREWALL_SUCCESS = "GET_LIST_FIREWALL_SUCCESS";
export const GET_LIST_FIREWALL_FAILDED = "GET_LIST_FIREWALL_FAILDED";
export const ADD_FIREWALL = "ADD_FIREWALL";
export const ADD_FIREWALL_FAILED = "ADD_FIREWALL_FAILED";
export const DELETE_FIREWALL = "DELETE_FIREWALL";
export const DELETE_REDIRECTION = "DELETE_REDIRECTION";
export const DELETE_PAGE_RULE = "DELETE_PAGE_RULE";
export const DELETE_CACHE = "DELETE_CACHE";
export const DELETE_RATE_LIMIT = "DELETE_RATE_LIMIT"
export const UPDATE_REDIRECTION = "UPDATE_REDIRECTION";
export const DELETE_FIREWALL_FAILED = "DELETE_FIREWALL_FAILED";
export const GET_FIREWALL = "GET_FIREWALL";
export const GET_FIREWALL_SUCCESS = "GET_FIREWALL_SUCCESS";
export const GET_FIREWALL_FAIELD = "GET_FIREWALL_FAIELD";
export const RESET_GET_FIREWALL = "RESET_GET_FIREWALL";
export const GET_LIST_GLOBAL_RULES = "GET_LIST_GLOBAL_RULES";
export const GET_LIST_GLOBAL_RULES_SUCCESS = "GET_LIST_GLOBAL_RULES_SUCCESS";
export const GET_LIST_GLOBAL_RULES_ERROR = "GET_LIST_GLOBAL_RULES_ERROR";
export const RESET_GET_GLOBAL_RULE = "RESET_GET_GLOBAL_RULE";
export const ADD_GLOBAL_RULE = "ADD_GLOBAL_RULE";
export const UPDATE_GLOBAL_RULE = "UPDATE_GLOBAL_RULE";
export const UPDATE_STATUS_GLOBAL = "UPDATE_STATUS_GLOBAL";
export const DELETE_GLOBAL_RULE = "DELETE_GLOBAL_RULE";
export const UPDATE_FIREWALL = "UPDATE_FIREWALL";
export const UPDATE_FIREWALL_FAILED = "UPDATE_FIREWALL_FAILED";
export const SHOW_NOTIFICATION = "SHOW_NOTIFICATION";
export const GENERATE_FREE_SSL_ERROR = "GENERATE_FREE_SSL_ERROR";
export const CLEAR_NOTIFICATION_MESSAGE = "CLEAR_NOTIFICATION_MESSAGE";
export const UPDATE_STATUS_FIREWALL = "UPDATE_STATUS_FIREWALL";
export const UPDATE_STATUS_REDIRECTION = "UPDATE_STATUS_REDIRECTION";
export const UPDATE_STATUS_PAGE_RULE = "UPDATE_STATUS_PAGE_RULE";
export const UPDATE_STATUS_CACHE = "UPDATE_STATUS_CACHE";
export const UPDATE_STATUS_RATE_LIMIT = "UPDATE_STATUS_RATE_LIMIT";
export const GET_LIST_WAF = "GET_LIST_WAF";
export const GET_LIST_WAF_SUCCESS = "GET_LIST_WAF_SUCCESS";
export const GET_LIST_WAF_ERROR = "GET_LIST_WAF_ERROR";
export const GET_LIST_WAF_REDIRECTION = "GET_LIST_WAF_REDIRECTION";
export const RESET_GET_WAF_REDIRECTION = "RESET_GET_WAF_REDIRECTION";
export const GET_LIST_PAGE_RULE = "GET_LIST_PAGE_RULE";
export const GET_LIST_PAGE_RULE_SUCCESS = "GET_LIST_PAGE_RULE_SUCCESS";
export const GET_LIST_PAGE_RULE_ERROR  = "GET_LIST_PAGE_RULE_ERROR";
export const GET_LIST_WAF_REDIRECTION_SUCCESS = "GET_LIST_WAF_REDIRECTION_SUCCESS";
export const GET_LIST_WAF_REDIRECTION_ERROR = "GET_LIST_WAF_REDIRECTION_ERROR";
export const GET_LIST_CACHE = "GET_LIST_CACHE";
export const GET_LIST_CACHE_SUCCESS = "GET_LIST_CACHE_SUCCESS";
export const GET_LIST_CACHE_ERROR = "GET_LIST_CACHE_ERROR";
export const RESET_GET_CACHE = "RESET_GET_CACHE";
export const GET_LIST_RATE_LIMIT = "GET_LIST_RATE";
export const GET_LIST_RATE_LIMIT_SUCCESS = "GET_LIST_RATE_SUCCESS";
export const GET_LIST_RATE_LIMIT_ERROR = "GET_LIST_RATE_ERROR";
export const UPDATE_WAF = "UPDATE_WAF";
export const UPDATE_LIST_WAF = "UPDATE_LIST_WAF";
export const UPDATE_LIST_WAF_ERROR = "UPDATE_LIST_WAF_ERROR";
export const FILTER_DATA_LOG = "FILTER_DATA_LOG";
export const FILTER_DATA_LOG_SUCCESS = "FILTER_DATA_LOG_SUCCESS";
export const FILTER_DATA_LOG_ERROR = "FILTER_DATA_LOG_ERROR";
export const CLEAR_FILTER_DATA_LOG = "CLEAR_FILTER_DATA_LOG";
export const GET_REPORT_URI = "GET_REPORT_URI";
export const GET_REPORT_URI_SUCCESS = "GET_REPORT_URI_SUCCESS";
export const GET_REPORT_URI_ERROR = "GET_REPORT_URI_ERROR";
export const GET_ACCESS_LOG = "GET_ACCESS_LOG";
export const GET_ACCESS_LOG_SUCCESS = "GET_ACCESS_LOG_SUCCESS";
export const GET_ACCESS_LOG_ERROR = "GET_ACCESS_LOG_ERROR";
export const GET_DOMAIN = "GET_DOMAIN";
export const GET_DOMAIN_SUCCESS = "GET_DOMAIN_SUCCESS";
export const ADD_DOMAIN = "ADD_DOMAIN";
export const ADD_DOMAIN_ERROR = "ADD_DOMAIN_ERROR";
export const GET_DOMAIN_BY_CUSTOMER_ID = "GET_DOMAIN_BY_CUSTOMER_ID";
export const GET_DOMAIN_BY_CUSTOMER_ID_SUCCESS =
  "GET_DOMAIN_BY_CUSTOMER_ID_SUCCESS";
export const GET_DOMAIN_BY_CUSTOMER_ID_ERROR =
  "GET_DOMAIN_BY_CUSTOMER_ID_ERROR";
export const GET_REPORT_URI_DETAIL = "GET_REPORT_URI_DETAIL";
export const GET_REPORT_URI_DETAIL_SUCCESS = "GET_REPORT_URI_DETAIL_SUCCESS";
export const GET_REPORT_URI_DETAIL_ERROR = "GET_REPORT_URI_DETAIL_ERROR";
export const GET_RATE_LIMIT = "GET_RATE_LIMIT";
export const GET_RATE_LIMIT_SUCCESS = "GET_RATE_LIMIT_SUCCESS";
export const GET_RATE_LIMIT_FAILED = "GET_RATE_LIMIT_FAILED";
export const RESET_GET_RATE_LIMIT = "RESET_GET_RATE_LIMIT";
export const UPDATE_RATE_LIMIT = "UPDATE_RATE_LIMIT";
export const UPDATE_RATE_LIMIT_SUCCESS = "UPDATE_RATE_LIMIT_SUCCESS";
export const ADD_NEW_ROW_RATE_LIMIT = "ADD_NEW_ROW_RATE_LIMIT";
export const REMOVE_ROW_RATE_LIMIT = "REMOVE_ROW_RATE_LIMIT";
export const GET_ACTIVE_PLAN = "GET_ACTIVE_PLAN";
export const GET_ACTIVE_PLAN_SUCCESS = "GET_ACTIVE_PLAN_SUCCESS";
export const GET_ACTIVE_PLAN_BY_ID = "GET_ACTIVE_PLAN_BY_ID";
export const GET_ACTIVE_PLAN_BY_ID_SUCCESS =
  "GET_ACTIVE_PLAN_BY_ID_SUCCESS";
export const PROCESS_PAYMENT_FOR_DOMAIN = "PROCESS_PAYMENT_FOR_DOMAIN";
export const GET_CUSTOMER_BY_ID = "GET_CUSTOMER_BY_ID";
export const GET_CUSTOMER_BY_ID_SUCCESS = "GET_CUSTOMER_BY_ID_SUCCESS";
export const GET_CUSTOMERS = "GET_CUSTOMERS";
export const GET_CUSTOMERS_SUCCESS = "GET_CUSTOMERS_SUCCESS";
export const DOWNLOAD_CUSTOMER_DATA = "DOWNLOAD_CUSTOMER_DATA";
export const DOWNLOAD_CUSTOMER_DATA_SUCCESS = "DOWNLOAD_CUSTOMER_DATA_SUCCESS";
export const DOWNLOAD_CUSTOMER_DATA_ERROR = "DOWNLOAD_CUSTOMER_DATA_ERROR";
export const ADD_OR_UPDATE_CUSTOMER = "ADD_OR_UPDATE_CUSTOMER";
export const SPIN_TABLE_LOADING = "SPIN_TABLE_LOADING";
export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";
export const VERIFY_TWO_FACTOR_AUTH = "VERIFY_TWO_FACTOR_AUTH";
export const VERIFY_TWO_FACTOR_AUTH_ERROR = "VERIFY_TWO_FACTOR_AUTH_ERROR";
export const FORGOT_PASSWORD = "FORGOT_PASSWORD";
export const FORGOT_PASSWORD_ERROR = "FORGOT_PASSWORD_ERROR";
export const RESET_PASSWORD = "RESET_PASSWORD";
export const RESET_PASSWORD_ERROR = "RESET_PASSWORD_ERROR";
export const RESEND_CODE_EMAIL = "RESEND_CODE_EMAIL";
export const RESEND_CODE_EMAIL_SUCCESS = "RESEND_CODE_EMAIL_SUCCESS";
export const RESEND_CODE_EMAIL_FAILED = "RESEND_CODE_EMAIL_FAILED";
export const GET_REPORT_TRAFFIC_BY_DOMAIN_ID =
  "GET_REPORT_TRAFFIC_BY_DOMAIN_ID";
export const GET_REPORT_TRAFFIC_BY_DOMAIN_ID_SUCCESS =
  "GET_REPORT_TRAFFIC_BY_DOMAIN_ID_SUCCESS";
export const GET_REPORT_TRAFFIC_BY_DOMAIN_ID_ERROR =
  "GET_REPORT_TRAFFIC_BY_DOMAIN_ID_ERROR";
export const GET_TOTAL_DATA_DASHBOARD = "GET_TOTAL_DATA_DASHBOARD";
export const GET_TOTAL_DATA_DASHBOARD_SUCCESS =
  "GET_TOTAL_DATA_DASHBOARD_SUCCESS";
export const CHECK_DUPLICATE_DOMAIN = "CHECK_DUPLICATE_DOMAIN";
export const CHECK_DUPLICATE_DOMAIN_SUCCESS = "CHECK_DUPLICATE_DOMAIN_SUCCESS";
export const RESET_DATA_LOGIN = "RESET_DATA_LOGIN";
export const GET_DOMAIN_BY_CUSTOMER_ID_FOR_REPORT_TRAFFIC =
  "GET_DOMAIN_BY_CUSTOMER_ID_FOR_REPORT_TRAFFIC";
export const GET_DOMAIN_BY_CUSTOMER_ID_FOR_REPORT_TRAFFIC_SUCCESS =
  "GET_DOMAIN_BY_CUSTOMER_ID_FOR_REPORT_TRAFFIC_SUCCESS";

export const RESET_GET_DOMAIN = "RESET_GET_DOMAIN";
export const GET_REPORT_REQUEST_BY_DOMAIN = "GET_REPORT_REQUEST_BY_DOMAIN";
export const GET_REPORT_REQUEST_BY_DOMAIN_SUCCESS =
  "GET_REPORT_REQUEST_BY_DOMAIN_SUCCESS";
export const GET_REPORT_REQUEST_BY_DOMAIN_ERROR =
  "GET_REPORT_REQUEST_BY_DOMAIN_ERROR";
export const GET_REPORT_HTTP_CODE_BY_DOMAIN = "GET_REPORT_HTTP_CODE_BY_DOMAIN";
export const GET_REPORT_HTTP_CODE_BY_DOMAIN_SUCCESS =
  "GET_REPORT_HTTP_CODE_BY_DOMAIN_SUCCESS";
export const GET_REPORT_HTTP_CODE_BY_DOMAIN_ERROR =
  "GET_REPORT_HTTP_CODE_BY_DOMAIN_ERROR";
export const SPIN_BUTTON_LOADING = "SPIN_BUTTON_LOADING";
export const GET_DOMAIN_ADVANCE_CONFIG_BY_ID =
  "GET_DOMAIN_ADVANCE_CONFIG_BY_ID";
export const GET_DOMAIN_ADVANCE_CONFIG_BY_ID_SUCCESS =
  "GET_DOMAIN_ADVANCE_CONFIG_BY_ID_SUCCESS";
export const ADVANCE_CONFIG_FOR_DOMAIN = "ADVANCE_CONFIG_FOR_DOMAIN";
export const ADVANCE_CONFIG_FOR_DOMAIN_SUCCESS =
  "ADVANCE_CONFIG_FOR_DOMAIN_SUCCESS";
export const GET_DOMAIN_REDIRECTION_BY_ID =
  "GET_DOMAIN_REDIRECTION_BY_ID";
export const GET_DOMAIN_REDIRECTION_BY_ID_SUCCESS =
  "GET_DOMAIN_REDIRECTION_BY_ID_SUCCESS";
export const UPDATE_DOMAIN_REDIRECTION = "UPDATE_DOMAIN_REDIRECTION";
export const UPDATE_DOMAIN_REDIRECTION_SUCCESS =
  "UPDATE_DOMAIN_REDIRECTION_SUCCESS";
export const GET_TOP_DOMAIN_TRAFFIC = "GET_TOP_DOMAIN_TRAFFIC";
export const GET_TOP_DOMAIN_TRAFFIC_SUCCESS = "GET_TOP_DOMAIN_TRAFFIC_SUCCESS";
export const GET_TOP_DOMAIN_TRAFFIC_ERROR = "GET_TOP_DOMAIN_TRAFFIC_ERROR";
export const UPLOAD_SSL_FILE = "UPLOAD_SSL_FILE";
export const UPLOAD_SSL_FILE_ERROR = "UPLOAD_SSL_FILE_ERROR";
export const UPLOAD_MUTUAL_SSL_FILE = "UPLOAD_MUTUAL_SSL_FILE";
export const UPLOAD_MUTUAL_SSL_FILE_ERROR = "UPLOAD_MUTUAL_SSL_FILE_ERROR";
export const UPLOAD_MUTUAL_ORIGIN_FILE = "UPLOAD_MUTUAL_ORIGIN_FILE";
export const UPLOAD_MUTUAL_ORIGIN_FILE_ERROR = "UPLOAD_MUTUAL_SSL_FILE_ERROR";
export const GET_SSL = "GET_SSL";
export const GET_SSL_SUCCESS = "GET_SSL_SUCCESS";
export const GET_MUTUAL_SSL = "GET_MUTUAL_SSLL";
export const GET_MUTUAL_SSL_SUCCESS = "GET_MUTUAL_SSL_SUCCESS";
export const GET_MUTUAL_SSL_ERROR = "GET_MUTUAL_SSL_ERROR";
export const GET_MUTUAL_ORIGIN = "GET_MUTUAL_ORIGIN";
export const FILTER_DATA_LOG_RESET = "FILTER_DATA_LOG_RESET";
export const VERIFY_CODE_REGISTER = "VERIFY_CODE_REGISTER";
export const VERIFY_CODE_REGISTER_SUCCESS = "VERIFY_CODE_REGISTER_SUCCESS";
export const VERIFY_CODE_REGISTER_ERROR = "VERIFY_CODE_REGISTER_ERROR";
export const DELETE_DOMAIN = "DELETE_DOMAIN";
export const DELETE_DOMAIN_FAILED = "DELETE_DOMAIN_FAILED";
export const ADVANCE_SSL_SETTING = "ADVANCE_SSL_SETTING";
export const ADVANCE_SSL_SETTING_SUCCESS = "ADVANCE_SSL_SETTING_SUCCESS";
export const GET_DETAIL_SSL = "GET_DETAIL_SSL";
export const GET_DETAIL_SSL_SUCCESS = "GET_DETAIL_SSL_SUCCESS";
export const GET_DETAIL_SSL_ERROR = "GET_DETAIL_SSL_ERROR";
export const CHECK_EXCEEDED_LIMIT_OF_DOMAINS =
  "CHECK_EXCEEDED_LIMIT_OF_DOMAINS";
export const CHECK_EXCEEDED_LIMIT_OF_DOMAINS_SUCCESS =
  "CHECK_EXCEEDED_LIMIT_OF_DOMAINS_SUCCESS";
export const ADD_ORIGIN = "ADD_ORIGIN";
export const GET_LIST_ORIGIN = "GET_LIST_ORIGIN";
export const GET_LIST_ORIGIN_SUCCESS = "GET_LIST_ORIGIN_SUCCESS";
export const GET_LIST_ORIGIN_ERROR = "GET_LIST_ORIGIN_ERROR";
export const GET_ORIGIN = "GET_ORIGIN";
export const GET_ORIGIN_SUCCESS = "GET_ORIGIN_SUCCESS";
export const UPDATE_ORIGIN = "UPDATE_ORIGIN";
export const DELETE_ORIGIN = "DELETE_ORIGIN";
export const DELETE_ORIGIN_SUCCESS = "DELETE_ORIGIN_SUCCESS";
export const GET_PAD = "GET_PAD";
export const GET_PAD_SUCCESS = "GET_PAD_SUCCESS";
export const UPDATE_ROUND_ROBIN = "UPDATE_ROUND_ROBIN";
export const UPDATE_ROUND_ROBIN_SUCCESS = "UPDATE_ROUND_ROBIN_SUCCESS";
export const UPDATE_STATUS_ORIGIN = "UPDATE_STATUS_ORIGIN";
export const UPDATE_STATUS_ORIGIN_SUCCESS = "UPDATE_STATUS_ORIGIN_SUCCESS";
export const UPDATE_BACKUP_ORIGIN = "UPDATE_BACKUP_ORIGIN";
export const UPDATE_BACKUP_ORIGIN_SUCCESS = "UPDATE_BACKUP_ORIGIN_SUCCESS";
export const CREATE_CUSTOMER_SOURCE = "CREATE_CUSTOMER_SOURCE";
export const CREATE_CUSTOMER_SOURCE_SUCCESS = "CREATE_CUSTOMER_SOURCE_SUCCESS";
export const GET_TOP_DOMAIN_ATTACK = "GET_TOP_DOMAIN_ATTACK";
export const GET_TOP_DOMAIN_ATTACK_SUCCESS = "GET_TOP_DOMAIN_ATTACK_SUCCESS";
export const GET_TOP_DOMAIN_ATTACK_ERROR = "GET_TOP_DOMAIN_ATTACK_ERROR";
export const GET_ATTACK_DATE_BY_DOMAIN = "GET_ATTACK_DATE_BY_DOMAIN";
export const GET_ATTACK_DATE_BY_DOMAIN_SUCCESS =
  "GET_ATTACK_DATE_BY_DOMAIN_SUCCESS";
export const GET_ATTACK_DATE_BY_DOMAIN_ERROR =
  "GET_ATTACK_DATE_BY_DOMAIN_ERROR";
export const GET_OWASP_BY_DOMAIN = "GET_OWASP_BY_DOMAIN";
export const GET_OWASP_BY_DOMAIN_SUCCESS = "GET_OWASP_BY_DOMAIN_SUCCESS";
export const GET_OWASP_BY_DOMAIN_ERROR = "GET_OWASP_BY_DOMAIN_ERROR";
export const GET_RULE_TRIGGER_BY_DOMAIN = "GET_RULE_TRIGGER_BY_DOMAIN";
export const GET_RULE_TRIGGER_BY_DOMAIN_SUCCEESS =
  "GET_RULE_TRIGGER_BY_DOMAIN_SUCCEESS";
export const GET_RULE_TRIGGER_BY_DOMAIN_ERROR =
  "GET_RULE_TRIGGER_BY_DOMAIN_ERROR";
export const GET_ATTACK_LOG_BY_DOMAIN = "GET_ATTACK_LOG_BY_DOMAIN";
export const GET_ATTACK_LOG_BY_DOMAIN_SUCCESS =
  "GET_ATTACK_LOG_BY_DOMAIN_SUCCESS";
export const GET_ATTACK_LOG_BY_DOMAIN_ERROR = "GET_ATTACK_LOG_BY_DOMAIN_ERROR";
export const GET_LIST_CUSTOMERS = "GET_LIST_CUSTOMERS";
export const GET_LIST_CUSTOMER_SUCCESS = "GET_LIST_CUSTOMER_SUCCESS";
export const GET_LIST_CUSTOMER_FAILDED = "GET_LIST_CUSTOMER_FAILDED";
export const RESET_GET_CUSTOMER = "RESET_GET_CUSTOMER"
export const DELETE_CUSTOMER = "DELETE_CUSTOMER";
export const DELETE_CUSTOMER_SUCCESS = "DELETE_CUSTOMER_SUCCESS";
export const DISABLE_2FA_WITH_AUTHENTICATOR = "DISABLE_2FA_WITH_AUTHENTICATOR";
export const DISABLE_SINGPASS_LOGIN = "DISABLE_SINGPASS_LOGIN";
export const ENABLE_LOGIN_WITH_OIDC = "ENABLE_LOGIN_WITH_OIDC";
export const DISABLE_LOGIN_WITH_OIDC = "DISABLE_LOGIN_WITH_OIDC";
export const GET_2FA_QRCODE = "GET_2FA_QRCODE";
export const GET_2FA_QRCODE_SUCCESS = "GET_2FA_QRCODE_SUCCESS";
export const ENABLE_2FA_WITH_AUTHENTICATOR = "ENABLE_2FA_WITH_AUTHENTICATOR";
export const CHANGE_PASSWORD = "CHANGE_PASSWORD";
export const CHANGE_PASSWORD_ERROR = "CHANGE_PASSWORD_ERROR";
export const GET_LIST_USERS = "GET_LIST_USERS";
export const GET_LIST_USERS_SUCCESS = "GET_LIST_USERS_SUCCESS";
export const GET_LIST_USERS_FAILDED = "GET_LIST_USERS_FAILDED";
export const RESET_GET_USER = "RESET_GET_USER";
export const DELETE_USER = "DELETE_USER";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const EDIT_STATUS_USER = "EDIT_STATUS_USER";
export const EDIT_STATUS_USER_SUCCESS = "EDIT_STATUS_USER_SUCCESS";
export const ADD_USER = "ADD_USER";
export const ADD_USER_ERROR = "ADD_USER_ERROR";
export const EDIT_USER = "EDIT_USER";
export const GET_USER_BY_ID = "GET_USER_BY_ID";
export const GET_USER_BY_ID_SUCCESS = "GET_USER_BY_ID_SUCCESS";
export const GET_ALL_INVOICES = "GET_ALL_INVOICES";
export const GET_ALL_INVOICES_SUCCESS = "GET_ALL_INVOICES_SUCCESS";
export const GET_ALL_INVOICES_FAILDED = "GET_ALL_INVOICES_FAILDED";
export const GET_INVOICE_BY_ID = "GET_INVOICE_BY_ID";
export const GET_INVOICE_BY_ID_SUCCESS = "GET_INVOICE_BY_ID_SUCCESS";
export const CHECK_VALID_DOMAIN = "CHECK_VALID_DOMAIN";
export const CHECK_VALID_DOMAIN_SUCCESS = "CHECK_VALID_DOMAIN_SUCCESS";
export const DOWNLOAD_REPORT_LOG = "DOWNLOAD_REPORT_LOG";
export const DOWNLOAD_REPORT_LOG_SUCCESS = "DOWNLOAD_REPORT_LOG_SUCCESS";
export const DOWNLOAD_REPORT_LOG_ERROR = "DOWNLOAD_REPORT_LOG_ERROR";
export const CLEAR_DOWNLOAD_REPORT_LOG = "CLEAR_DOWNLOAD_REPORT_LOG";
export const ADD_SCHEDULER_REPORT = "ADD_SHEDULER_REPORT";
export const ADD_SCHEDULER_REPORT_ERROR = "ADD_SHEDULER_REPORT_ERROR";
export const EDIT_SCHEDULER_REPORT = "EDIT_SCHEDULER_REPORT";
export const EDIT_SCHEDULER_REPORT_ERROR = "EDIT_SCHEDULER_REPORT_ERROR";
export const GET_SCHEDULER_REPORT = "GET_SCHEDULER_REPORT";
export const GET_SCHEDULER_REPORT_SUCCESS = "GET_SCHEDULER_REPORT_SUCCESS";
export const DELETE_SCHEDULER_REPORT = "DELETE_SCHEDULER_REPORT";
export const SET_DEFAULT_CONFIG_FOR_DOMAIN = "SET_DEFAULT_CONFIG_FOR_DOMAIN";
export const GET_DEFAULT_CONFIG_BY_PADID = "GET_DEFAULT_CONFIG_BY_PADID";
export const GET_DEFAULT_CONFIG_BY_PADID_SUCCESS =
  "GET_DEFAULT_CONFIG_BY_PADID_SUCCESS";
export const GET_REPORT_IP = "GET_REPORT_IP";
export const GET_REPORT_IP_SUCCESS = "GET_REPORT_IP_SUCCESS";
export const GET_REPORT_IP_ERROR = "GET_REPORT_IP_ERROR";
export const LOG_UPGRADE_ACTION = "LOG_UPGRADE_ACTION";
export const APPLY_DISCOUNT_CODE = "APPLY_DISCOUNT_CODE";
export const APPLY_DISCOUNT_CODE_SUCCESS = "APPLY_DISCOUNT_CODE_SUCCESS";
export const CHECK_POINTED_CNAME_TO_DOMAIN = "CHECK_POINTED_CNAME_TO_DOMAIN";
export const CHECK_POINTED_CNAME_TO_DOMAIN_SUCCESS ="CHECK_POINTED_CNAME_TO_DOMAIN_SUCCESS";
export const SSL_COOKIES_SETTING = "SSL_COOKIES_SETTING";
export const SSL_COOKIES_SETTING_SUCCESS = "SSL_COOKIES_SETTING_SUCCESS";
export const GET_BAND_WIDTH_REPORT = "GET_BAND_WIDTH_REPORT";
export const GET_BAND_WIDTH_REPORT_SUCCESS = "GET_BAND_WIDTH_REPORT_SUCCESS";
export const GET_BAND_WIDTH_REPORT_ERROR = "GET_BAND_WIDTH_REPORT_ERROR";
export const CHECK_POINTED_SSL_TO_DOMAIN = "CHECK_POINTED_SSL_TO_DOMAIN";
export const CHECK_POINTED_SSL_TO_DOMAIN_SUCCESS =
  "CHECK_POINTED_SSL_TO_DOMAIN_SUCCESS";
export const CHECK_DUPLICATE_DOMAIN_ERROR = "CHECK_DUPLICATE_DOMAIN_ERROR";
export const CHECK_VALID_DOMAIN_ERROR = "CHECK_VALID_DOMAIN_ERROR";
export const CLEAR_CACHE_DOMAIN = "CLEAR_CACHE_DOMAIN";
export const RESEND_EMAIL_ACTIVE = "RESEND_EMAIL_ACTIVE";
export const ACCESS_TOKEN = "ACCESS_TOKEN";
export const ADD_USER_SUCCESS = "ADD_USER_SUCCESS";
export const CREATE_CHECKOUT_SESSION = "CREATE_CHECKOUT_SESSION";
export const CREATE_CHECKOUT_SESSION_SUCCESS =
  "CREATE_CHECKOUT_SESSION_SUCCESS";
export const ADD_CUSTOMER_WITH_OWNER_USER = "ADD_CUSTOMER_WITH_OWNER_USER";
export const ADD_CUSTOMER_WITH_OWNER_USER_ERROR =
  "ADD_CUSTOMER_WITH_OWNER_USER_ERROR";
export const ADD_CUSTOMER_WITH_OWNER_USER_SUCCESS =
  "ADD_CUSTOMER_WITH_OWNER_USER_SUCCESS";
export const INQUIRY_FOR_ENTERPRISE_PLAN = "INQUIRY_FOR_ENTERPRISE_PLAN";
export const GET_INQUIRY_FOR_ENTERPRISE_PLAN =
  "GET_INQUIRY_FOR_ENTERPRISE_PLAN";
export const GET_INQUIRY_FOR_ENTERPRISE_PLAN_SUCCESS =
  "GET_INQUIRY_FOR_ENTERPRISE_PLAN_SUCCESS";
export const ADD_PLAN_FOR_CUSTOMER = "ADD_PLAN_FOR_CUSTOMER";
export const ADD_PLAN_FOR_CUSTOMER_SUCCESS = "ADD_PLAN_FOR_CUSTOMER_SUCCESS";
export const ADD_PLAN_FOR_CUSTOMER_ERROR = "ADD_PLAN_FOR_CUSTOMER_ERROR";
export const GET_LAST_SUBSCRIBER_CUSTOMER = "GET_LAST_SUBSCRIBER_CUSTOMER";
export const GET_LAST_SUBSCRIBER_CUSTOMER_SUCCESS =
  "GET_LAST_SUBSCRIBER_CUSTOMER_SUCCESS";
export const GET_LAST_SUBSCRIBER_CUSTOMER_ERROR =
  "GET_LAST_SUBSCRIBER_CUSTOMER_ERROR";
export const GET_LIST_BASE_SECURITY = "GET_LIST_BASE_SECURITY";
export const GET_LIST_BASE_SECURITY_SUCCESS = "GET_LIST_BASE_SECURITY_SUCCESS";
export const GET_LIST_BASE_SECURITY_ERROR = "GET_LIST_BASE_SECURITY_ERROR";
export const ADD_BASE_SECURITY = "ADD_BASE_SECURITY";
export const ADD_REDIRECTION = "ADD_REDIRECTION";
export const ADD_BASE_SECURITY_ERROR = "ADD_BASE_SECURITY_ERROR";
export const GET_BASE_SECURITY = "GET_BASE_SECURITY";
export const GET_BASE_SECURITY_SUCCESS = "GET_BASE_SECURITY_SUCCESS";
export const GET_BASE_SECURITY_ERROR = "GET_BASE_SECURITY_ERROR";
export const RESET_GET_BASE_SECURITY = "RESET_GET_BASE_SECURITY";
export const DELETE_BASE_SECURITY = "DELETE_BASE_SECURITY";
export const DELETE_BASE_SECURITY_ERROR = "DELETE_BASE_SECURITY_ERROR";
export const UPDATE_BASE_SECURITY = "UPDATE_BASE_SECURITY";
export const UPDATE_BASE_SECURITY_ERROR = "UPDATE_BASE_SECURITY_ERROR";
export const UPDATE_STATUS_BASE_SECURITY = "UPDATE_STATUS_BASE_SECURITY";
export const UPDATE_STATUS_BASE_SECURITY_SUCCESS =
  "UPDATE_STATUS_BASE_SECURITY_SUCCESS";
export const GET_ALL_AUDIT_LOG = "GET_ALL_AUDIT_LOG";
export const GET_ALL_AUDIT_LOG_SUCCESS = "GET_ALL_AUDIT_LOG_SUCCESS";
export const GET_ALL_AUDIT_LOG_ERROR = "GET_ALL_AUDIT_LOG_ERROR";
export const GET_PERMISSION_CONFIGURATION = "GET_PERMISSION_CONFIGURATION";
export const GET_PERMISSION_CONFIGURATION_SUCCESS =
  "GET_PERMISSION_CONFIGURATION_SUCCESS";
export const GET_PERMISSION_CONFIGURATION_ERROR =
  "GET_PERMISSION_CONFIGURATION_ERROR";
export const PURCHASE_FEATURE_PERMISSION = "PURCHASE_FEATURE_PERMISSION";
export const UPDATE_INFO_AUTH_ME = "UPDATE_INFO_AUTH_ME";
export const GET_LIST_DOMAIN_FOR_FILTER = "GET_LIST_DOMAIN_FOR_FILTER";
export const GET_LIST_DOMAIN_FOR_FILTER_SUCCESS =
  "GET_LIST_DOMAIN_FOR_FILTER_SUCCESS";
export const GET_LIST_DOMAIN_FOR_FILTER_ERROR =
  "GET_LIST_DOMAIN_FOR_FILTER_ERROR";
export const GET_BINDING_IP_TABLE_FOR_DOMAIN =
  "GET_BINDING_IP_TABLE_FOR_DOMAIN";
export const GET_BINDING_IP_TABLE_FOR_DOMAIN_SUCCESS =
  "GET_BINDING_IP_TABLE_FOR_DOMAIN_SUCCESS";
export const SAVE_BINDING_IP_TABLE_FOR_DOMAIN =
  "SAVE_BINDING_IP_TABLE_FOR_DOMAIN";
export const SAVE_BINDING_IP_TABLE_FOR_DOMAIN_SUCCESS =
  "SAVE_BINDING_IP_TABLE_FOR_DOMAIN_SUCCESS";
export const GET_DOMAIN_FOR_EDIT = "GET_DOMAIN_FOR_EDIT";
export const GET_DOMAIN_FOR_EDIT_SUCCESS = "GET_DOMAIN_FOR_EDIT_SUCCESS";
export const EDIT_DOMAIN = "EDIT_DOMAIN";
export const BACKUP_ORIGIN = "BACKUP_ORIGIN";
export const BACKUP_ORIGIN_SUCCESS = "BACKUP_ORIGIN_SUCCESS";
export const ENABLE_WHITELIST_ORIGIN = "ENABLE_WHITELIST_ORIGIN";
export const ENABLE_WHITELIST_ORIGIN_SUCCESS =
  "ENABLE_WHITELIST_ORIGIN_SUCCESS";
export const GET_ENABLE_WHITELIST = "GET_ENABLE_WHITELIST";
export const GET_ENABLE_WHITELIST_SUCCESS = "GET_ENABLE_WHITELIST_SUCCESS";
export const GET_ENABLE_WHITELIST_ERROR = "GET_ENABLE_WHITELIST_ERROR";
export const UPDATE_STATUS_DOMAIN = "UPDATE_STATUS_DOMAIN";
export const GET_REPORT_CACHE_RATIO = "GET_REPORT_CACHE_RATIO";
export const GET_REPORT_CACHE_RATIO_SUCCESS = "GET_REPORT_CACHE_RATIO_SUCCESS";
export const GET_REPORT_CACHE_RATIO_ERROR = "GET_REPORT_CACHE_RATIO_ERROR";
export const CHECK_VALID_ORIGIN_PORT = "CHECK_VALID_ORIGIN_PORT";
export const CHECK_VALID_ORIGIN_PORT_SUCCESS =
  "CHECK_VALID_ORIGIN_PORT_SUCCESS";
export const CHECK_VALID_ORIGIN_PORT_ERROR = "CHECK_VALID_ORIGIN_PORT_ERROR";
export const CHECK_IS_CUSTOMER_EXISTED = "CHECK_IS_CUSTOMER_EXISTED";
export const CHECK_IS_CUSTOMER_EXISTED_SUCCESS =
  "CHECK_IS_CUSTOMER_EXISTED_SUCCESS";
export const CHECK_IS_CUSTOMER_EXISTED_ERROR =
  "CHECK_IS_CUSTOMER_EXISTED_ERROR";
export const CHECK_IS_CUSTOMER_EXISTED_RESET =
  "CHECK_IS_CUSTOMER_EXISTED_RESET";
export const SSL_NOT_POINTED = "SSL_NOT_POINTED";
export const CHANGE_TO_NEW_SSL = "CHANGE_TO_NEW_SSL";
export const GET_OWASP_RULES = "GET_OWASP_RULES";
export const GET_OWASP_RULES_SUCCESS = "GET_OWASP_RULES_SUCCESS";
export const GET_OWASP_RULES_ERROR = "GET_OWASP_RULES_ERROR";
export const GET_ALL_DISABLED_OWASP_RULES = "GET_ALL_DISABLED_OWASP_RULES";
export const GET_ALL_DISABLED_OWASP_RULES_SUCCESS =
  "GET_ALL_DISABLED_OWASP_RULES_SUCCESS";
export const GET_ALL_DISABLED_OWASP_RULES_ERROR =
  "GET_ALL_DISABLED_OWASP_RULES_ERROR";
export const DISABLE_OWASP_RULE = "DISABLE_OWASP_RULE";
export const DISABLE_OWASP_RULE_SUCCESS = "DISABLE_OWASP_RULE_SUCCESS";
export const DISABLE_OWASP_RULE_ERROR = "DISABLE_OWASP_RULE_ERROR";
export const REMOVE_DISABLED_OWASP_RULE = "REMOVE_DISABLED_OWASP_RULE";
export const REMOVE_DISABLED_OWASP_RULE_SUCCESS =
  "REMOVE_DISABLED_OWASP_RULE_SUCCESS";
export const REMOVE_DISABLED_OWASP_RULE_ERROR =
  "REMOVE_DISABLED_OWASP_RULE_ERROR";
export const GET_LIST_LOGIN_TYPE = "GET_LIST_LOGIN_TYPE";
export const GET_LIST_LOGIN_TYPE_SUCCESS = "GET_LIST_LOGIN_TYPE_SUCCESS";
export const GET_LIST_LOGIN_TYPE_ERROR = "GET_LIST_LOGIN_TYPE_ERROR";
export const ADD_LOGIN_TYPE = "ADD_LOGIN_TYPE";
export const ADD_LOGIN_TYPE_SUCCESS = "ADD_LOGIN_TYPE_SUCCESS";
export const ADD_LOGIN_TYPE_ERROR = "ADD_LOGIN_TYPE_ERROR";
export const EDIT_LOGIN_TYPE = "EDIT_LOGIN_TYPE";
export const EDIT_LOGIN_TYPE_SUCCESS = "EDIT_LOGIN_TYPE_SUCCESS";
export const EDIT_LOGIN_TYPE_ERROR = "EDIT_LOGIN_TYPE_ERROR";
export const GET_LIST_IPS = "GET_LIST_IPS";
export const GET_LIST_IPS_SUCCESS = "GET_LIST_IPS_SUCCESS";
export const GET_LIST_IPS_FAILED = "GET_LIST_IPS_FAILED";
export const GET_IP_BY_ID = "GET_IP_BY_ID";
export const GET_IP_BY_ID_FAILED = "GET_IP_BY_ID_FAILED";
export const GET_IP_BY_ID_SUCCESS = "GET_IP_BY_ID_SUCCESS";
export const RESET_GET_IP = "RESET_GET_IP";
export const CHECK_SERVER_EXISTED = "CHECK_SERVER_EXISTED";
export const CHECK_SERVER_EXISTED_SUCCESS = "CHECK_SERVER_EXISTED_SUCCESS";
export const CHECK_SERVER_EXISTED_ERROR = "CHECK_SERVER_EXISTED_ERROR";
export const CHECK_SERVER_EXISTED_RESET = "CHECK_SERVER_EXISTED_RESET";
export const ADD_SERVER = "ADD_SERVER";
export const ADD_SERVER_SUCCESS = "ADD_SERVER_SUCCESS";
export const ADD_SERVER_ERROR = "ADD_SERVER_ERROR";
export const EDIT_SERVER_STATUS = "EDIT_SERVER_STATUS";
export const EDIT_SERVER_STATUS_SUCCESS = "EDIT_SERVER_STATUS_SUCCESS";
export const EDIT_SERVER_STATUS_ERROR = "EDIT_SERVER_STATUS_ERROR";
export const EDIT_SERVER = "EDIT_SERVER";
export const DELETE_SERVER = "DELETE_SERVER";
export const DELETE_SERVER_SUCCESS = "DELETE_SERVER_SUCCESS";
export const DELETE_SERVER_ERROR = "DELETE_SERVER_ERROR";
export const GET_LOGIN_TYPE_BY_ID = "GET_LOGIN_TYPE_BY_ID";
export const GET_LOGIN_TYPE_BY_ID_SUCCESS = "GET_LOGIN_TYPE_BY_ID_SUCCESS";
export const GET_LOGIN_TYPE_BY_ID_ERROR = "GET_LOGIN_TYPE_BY_ID_ERROR";
export const RESET_LOGIN_TYPE = "RESET_LOGIN_TYPE"
export const DELETE_LOGIN_TYPE = "DELETE_LOGIN_TYPE";
export const DELETE_LOGIN_TYPE_SUCCESS = "DELETE_LOGIN_TYPE_SUCCESS";
export const DELETE_LOGIN_TYPE_ERROR = "DELETE_LOGIN_TYPE_ERROR";
export const GET_LIST_GROUP_ORIGIN = "GET_LIST_GROUP_ORIGIN";
export const GET_LIST_GROUP_ORIGIN_SUCCESS = "GET_LIST_GROUP_ORIGIN_SUCCESS";
export const GET_LIST_GROUP_ORIGIN_ERROR = "GET_LIST_GROUP_ORIGIN_ERROR";
export const ADD_GROUP_ORIGIN = "ADD_GROUP_ORIGIN";
export const ADD_GROUP_ORIGIN_SUCCESS = "ADD_GROUP_ORIGIN_SUCCESS";
export const ADD_GROUP_ORIGIN_ERROR = "ADD_GROUP_ORIGIN_ERROR";
export const EDIT_GROUP_ORIGIN = "EDIT_GROUP_ORIGIN";
export const EDIT_GROUP_ORIGIN_SUCCESS = "EDIT_GROUP_ORIGIN_SUCCESS";
export const EDIT_GROUP_ORIGIN_ERROR = "EDIT_GROUP_ORIGIN_ERROR";
export const GET_GROUP_ORIGIN_BY_ID = "GET_GROUP_ORIGIN_BY_ID";
export const GET_GROUP_ORIGIN_BY_ID_SUCCESS = "GET_GROUP_ORIGIN_BY_ID_SUCCESS";
export const GET_GROUP_ORIGIN_BY_ID_ERROR = "GET_GROUP_ORIGIN_BY_ID_ERROR";
export const ADD_GATEWAY_ORIGIN = "ADD_GATEWAY_ORIGIN";
export const CHECK_GATEWAY_PORT = "CHECK_GATEWAY_PORT";
export const CHECK_GATEWAY_PORT_SUCCESS = "CHECK_GATEWAY_PORT_SUCCESS";
export const CHECK_GATEWAY_PORT_ERROR = "CHECK_GATEWAY_PORT_ERROR";
export const GET_GATEWAY_ORIGIN_BY_ID = "GET_GATEWAY_ORIGIN_BY_ID";
export const GET_GATEWAY_ORIGIN_BY_ID_SUCCESS = "GET_GATEWAY_ORIGIN_BY_ID_SUCCESS";
export const GET_GATEWAY_ORIGIN_BY_ID_ERROR = "GET_GATEWAY_ORIGIN_BY_ID_ERROR";
export const EDIT_GATEWAY_ORIGIN = "EDIT_GATEWAY_ORIGIN";
export const DELETE_GATEWAY_GROUP_ORIGIN = "DELETE_GATEWAY_GROUP_ORIGIN";
export const DELETE_GATEWAY_ORIGIN = "DELETE_GATEWAY_ORIGIN"
export const GET_LIST_ROUTE = "GET_LIST_ROUTE";
export const GET_LIST_ROUTE_SUCCESS = "GET_LIST_ROUTE_SUCCESS";
export const GET_LIST_ROUTE_ERROR = "GET_LIST_ROUTE_ERROR";
export const ADD_ROUTE = "ADD_ROUTE";
export const ADD_ROUTE_SUCCESS = "ADD_ROUTE_SUCCESS";
export const ADD_ROUTE_ERROR = "ADD_ROUTE_ERROR";
export const GET_ROUTE_BY_ID = "GET_ROUTE_BY_ID";
export const GET_ROUTE_BY_ID_SUCCESS = "GET_ROUTE_BY_ID_SUCCESS";
export const GET_ROUTE_BY_ID_ERROR = "GET_ROUTE_BY_ID_ERROR";
export const EDIT_ROUTE = "EDIT_ROUTE";
export const EDIT_ROUTE_SUCCESS = "EDIT_ROUTE_SUCCESS";
export const EDIT_ROUTE_ERROR = "EDIT_ROUTE_ERROR";
export const DELETE_ROUTE = "DELETE_ROUTE";
export const DELETE_ROUTE_SUCCESS = "DELETE_ROUTE_SUCCESS";
export const DELETE_ROUTE_ERROR = "DELETE_ROUTE_ERROR";
export const EDIT_GROUP_ORIGIN_STATUS = "EDIT_GROUP_ORIGIN_STATUS";
export const EDIT_GROUP_ORIGIN_STATUS_SUCCESS = "EDIT_GROUP_ORIGIN_STATUS_SUCCESS";
export const EDIT_GROUP_ORIGIN_STATUS_ERROR = "EDIT_GROUP_ORIGIN_STATUS_ERROR";
export const EDIT_ORIGIN_STATUS = "EDIT_ORIGIN_STATUS";
export const EDIT_ORIGIN_STATUS_SUCCESS = "EDIT_ORIGIN_STATUS_SUCCESS";
export const EDIT_ORIGIN_STATUS_ERROR = "EDIT_ORIGIN_STATUS_ERROR";
export const EDIT_ROUTE_STATUS = "EDIT_ROUTE_STATUS";
export const EDIT_ROUTE_STATUS_SUCCESS = "EDIT_ROUTE_STATUS_SUCCESS";
export const EDIT_ROUTE_STATUS_ERROR = "EDIT_ROUTE_STATUS_ERROR";
export const EDIT_GROUP_ORIGIN_MODE = "EDIT_GROUP_ORIGIN_MODE";
export const CHECK_ROUTE = "CHECK_ROUTE";
export const CHECK_ROUTE_SUCCESS = "CHECK_ROUTE_SUCCESS";
export const CHECK_ROUTE_ERROR = "CHECK_ROUTE_ERROR";
export const CLEAR_IS_INVALID_ROUTE = "CLEAR_IS_INVALID_ROUTE";
export const EDIT_BACKUP_GATEWAY = "EDIT_BACKUP_GATEWAY";
export const GENERATE_FREE_SSL = "GENERATE_FREE_SSL";
export const GET_LIST_PERMISSION = "GET_LIST_PERMISSION";
export const GET_LIST_PERMISSION_SUCCESS = "GET_LIST_PERMISSION_SUCCESS";
export const GET_LIST_PERMISSION_ERROR = "GET_LIST_PERMISSION_ERROR";
export const GET_PERMISSION_USER_BY_ID = "GET_PERMISSION_USER_BY_ID";
export const GET_PERMISSION_USER_BY_ID_SUCCESS = "GET_PERMISSION_USER_BY_ID_SUCCESS";
export const GET_PERMISSION_USER_BY_ID_ERROR = "GET_PERMISSION_USER_BY_ID_ERROR";
export const EDIT_PERMISSION_USER = "EDIT_PERMISSION_USER";
export const EDIT_PERMISSION_USER_SUCCESS = "EDIT_PERMISSION_USER_SUCCESS";
export const EDIT_PERMISSION_USER_ERROR = "EDIT_PERMISSION_USER_ERROR";
export const UPDATE_PRIORITY_RULE_CACHE = "UPDATE_PRIORITY_RULE_CACHE";
export const UPDATE_PRIORITY_RULE_REDIRECT = "UPDATE_PRIORITY_RULE_REDIRECT";
export const GET_WHITELABEL = "GET_WHITELABEL";
export const GET_WHITELABEL_SUCCESS = "GET_WHITELABEL_SUCCESS";
export const GET_WHITELABEL_ERROR = "GET_WHITELABEL_ERROR";
export const GET_LIST_GATEWAY = "GET_LIST_GATEWAY";
export const GET_LIST_GATEWAY_SUCCESS = "GET_LIST_GATEWAY_SUCCESS";
export const GET_LIST_GATEWAY_ERROR = "GET_LIST_GATEWAY_ERROR";
export const RESET_GET_GATEWAY = "RESET_GET_GATEWAY";
export const ADD_GATEWAY = "ADD_GATEWAY";
export const EDIT_GATEWAY = "EDIT_GATEWAY";
export const DELETE_GATEWAY = "DELETE_GATEWAY";
export const ADD_OR_EDIT_CUSTOM_HEADER_ADVANCE_CONFIG = "ADD_OR_EDIT_CUSTOM_HEADER_ADVANCE_CONFIG"
