export const LOG_OUT = "LOG_OUT"
export const GET_WHITELABEL = "GET_WHITELABEL";
export const GET_WHITELABEL_SUCCESS = "GET_WHITELABEL_SUCCESS";
export const GET_WHITELABEL_ERROR = "GET_WHITELABEL_ERROR";
export const SHOW_NOTIFICATION = "SHOW_NOTIFICATION";
